services:
  web:
    build: .
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`ms-consulting.at`) || Host(`www.ms-consulting.at`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    restart: unless-stopped
