services:
  web:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`ms-consulting.at`) || Host(`www.ms-consulting.at`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=letsencrypt"
      - "traefik.http.services.web.loadbalancer.server.url=http://localhost:3000"
    restart: unless-stopped
